import clsx from 'clsx';
import { useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import type { TypeName } from '../../engine';
import { artSrc, useArtVariant } from '../cardArt';
import styles from './CardFrame.module.scss';

export type CardVariant = 'thumb' | 'full' | 'hero';

/**
 * The type accent — a card's identity colour, shown as a spine on the frame.
 * Grouped by feel rather than assigned thirteen arbitrary hues: the palette has to
 * stay legible at 3px wide.
 */
const TYPE_ACCENT: Record<TypeName, string> = {
  Beast: '#8a9a4a',
  Insect: '#7fa03a',
  Dragon: '#c2562f',
  Avian: '#6fa8c9',
  Aqua: '#4a7fc4',
  Warrior: '#c9a24a',
  Spellcaster: '#8f6bc4',
  Fiend: '#a3436b',
  Undead: '#6b7a8f',
  Machine: '#9aa3ad',
  Inferno: '#d4652f',
  Verdant: '#4e9f5a',
  Terra: '#a58a5e',
};

export function typeAccent(type: TypeName | undefined): string | undefined {
  return type ? TYPE_ACCENT[type] : undefined;
}

/**
 * Card illustration from public/card-art/ (generated by `npm run art`), wearing
 * whichever variant the player picked — see src/ui/cardArt.ts.
 *
 * Art coverage is incremental, so a missing file must degrade to a frame with no art
 * rather than a broken image. Failure is tracked by SRC rather than as a bare boolean:
 * switching variant has to re-try, and a sticky `failed` flag would black out a card
 * for the rest of the session because one of its alternates was missing.
 */
export function CardArtImage({
  id,
  className,
  onFail,
}: {
  id: string;
  className?: string;
  onFail?: (src: string) => void;
}) {
  const variant = useArtVariant(id);
  const [failedSrc, setFailedSrc] = useState<string | null>(null);
  const src = artSrc(id, variant);
  if (failedSrc === src) return null;
  return (
    <img
      className={clsx(styles['art'], className)}
      src={src}
      alt=""
      loading="lazy"
      draggable={false}
      onError={() => {
        setFailedSrc(src);
        onFail?.(src);
      }}
    />
  );
}

/**
 * A square portrait for list rows (deck pickers, lobby seats). Same incremental-art
 * contract as the card frame: a missing file becomes a type-tinted initial, not an
 * empty black square.
 */
export function CardPortrait({ id, name, type }: { id: string; name: string; type?: TypeName | undefined }) {
  const variant = useArtVariant(id);
  const [failedSrc, setFailedSrc] = useState<string | null>(null);
  const accent = typeAccent(type);
  if (failedSrc === artSrc(id, variant)) {
    return (
      <span
        className={styles['portraitFallback']}
        style={accent ? ({ '--card-accent': accent } as CSSProperties) : undefined}
        aria-hidden="true"
      >
        {name.trim().charAt(0)}
      </span>
    );
  }
  return <CardArtImage id={id} onFail={setFailedSrc} />;
}

export interface CardFrameProps {
  /** Card id — also the art filename. */
  id: string;
  name: ReactNode;
  variant?: CardVariant;
  /** Unit type; drives the accent spine. */
  type?: TypeName | undefined;
  /** Copies in a deck list, shown as ×N. */
  count?: number | undefined;
  /** SP cost badge, top-left of the frame. */
  cost?: ReactNode;
  /** Level badge, top-right of the frame. Units only — it reads as the card's rank. */
  level?: ReactNode;
  /** Type / kind line under the name. Level lives in its own badge, not here. */
  meta?: ReactNode;
  /** Stat chips (ATK / DEF / DC). */
  stats?: ReactNode;
  /** Keyword tags. */
  keywords?: ReactNode;
  /** Rules text — hero variant only, in practice. */
  rules?: ReactNode;
  /** Action buttons pinned to the bottom (hand cards). */
  actions?: ReactNode;
  /** Suppress the art well entirely (dense list rows). */
  noArt?: boolean;
  onClick?: (() => void) | undefined;
  onMouseEnter?: (() => void) | undefined;
  onMouseLeave?: (() => void) | undefined;
  className?: string;
  /** Extra classes when the card is in a highlighted state (e.g. newly drawn). */
  highlighted?: boolean;
}

export function CardFrame({
  id,
  name,
  variant = 'thumb',
  type,
  count,
  cost,
  level,
  meta,
  stats,
  keywords,
  rules,
  actions,
  noArt = false,
  onClick,
  onMouseEnter,
  onMouseLeave,
  className,
  highlighted = false,
}: CardFrameProps) {
  const accent = typeAccent(type);
  const style = accent ? ({ '--card-accent': accent } as CSSProperties) : undefined;

  // Art coverage is incremental. A card with no file gets a type-tinted plate
  // bearing its initial — the frame keeps its proportions and the set still reads
  // as one deck, where the old behaviour left a black rectangle.
  //
  // Tracked by SRC, not as a boolean: picking a different variant must re-try (see
  // CardArtImage), and a sticky flag would keep the fallback up forever.
  const artVariant = useArtVariant(id);
  const [failedSrc, setFailedSrc] = useState<string | null>(null);
  const artFailed = failedSrc === artSrc(id, artVariant);
  const initial = typeof name === 'string' ? name.trim().charAt(0) : '';

  const heading = (
    <div className={styles['name']}>
      <span className={styles['nameText']}>{name}</span>
      {count !== undefined && <span className={styles['count']}>×{count}</span>}
    </div>
  );

  // THE FRAME: the showcase card itself — art, the overlay hairline and brackets
  // (drawn in pseudo-elements), the corner badges, and the name plate.
  //
  // It is a region of its own rather than a loose art well because rules text and
  // action buttons must sit OUTSIDE it while the name, type and stats sit ON it.
  // That is the whole difference between a framed card and an illustration with a
  // caption, and it is what lets all three variants share one treatment.
  const frame = (
    <div className={styles['frame']}>
      {!noArt && (
        <div className={styles['artWrap']}>
          <CardArtImage id={id} onFail={setFailedSrc} />
          {artFailed && (
            <span className={styles['artFallback']} aria-hidden="true">
              {initial}
            </span>
          )}
        </div>
      )}
      {cost !== undefined && cost !== null && <span className={styles['cost']}>{cost}</span>}
      {level !== undefined && level !== null && <span className={styles['level']}>{level}</span>}
      <div className={styles['plate']}>
        {heading}
        {meta && <div className={styles['meta']}>{meta}</div>}
        {stats && <div className={styles['stats']}>{stats}</div>}
      </div>
    </div>
  );

  // Everything that cannot live on the card face. Omitted entirely when empty, so a
  // deck tile is exactly the frame and nothing else.
  const hasBody = Boolean(keywords || rules);
  const body = hasBody && (
    <div className={styles['body']}>
      {keywords && <div className={styles['keywords']}>{keywords}</div>}
      {rules && <div className={styles['rules']}>{rules}</div>}
    </div>
  );

  const classes = clsx(
    styles['card'],
    styles[variant],
    noArt && styles['noArt'],
    highlighted && styles['highlighted'],
    onClick && styles['interactive'],
    className,
  );

  const hover = { onMouseEnter, onMouseLeave };

  // A card carrying action buttons cannot itself be a button — nested buttons are
  // invalid. There, the frame forms the inspect target and the actions sit outside
  // it. Without actions the whole card is one button, which is simpler and gives a
  // bigger hit area.
  if (onClick && actions) {
    return (
      <div className={classes} style={style} {...hover}>
        <button type="button" className={styles['inspect']} onClick={onClick}>
          {frame}
          {body}
        </button>
        <div className={styles['actions']}>{actions}</div>
      </div>
    );
  }

  const inner = (
    <>
      {frame}
      {body}
      {actions && <div className={styles['actions']}>{actions}</div>}
    </>
  );

  if (onClick) {
    return (
      <button type="button" className={classes} style={style} onClick={onClick} {...hover}>
        {inner}
      </button>
    );
  }

  return (
    <div className={classes} style={style} {...hover}>
      {inner}
    </div>
  );
}
