// Terrain materials for the board — nine of them, generated rather than painted.
//
//   npm run terrain                                  # stylised, 1024
//   npm run terrain -- --style=photoreal --size=512
//   npm run terrain:all                              # every style x size
//   npm run terrain -- --surface=full                # full-res normal/occlusion
//   npm run terrain -- --fast                        # coarse, for iterating
//
// PROCEDURAL, not painted, and not generated by an image model. Three reasons that
// is the right call here and not just the cheap one:
//
//   1. They must TILE. A board is a grid of 49 cells drawn from nine terrains, so
//      a texture with a seam or a recognisable blob announces the repeat instantly.
//      Every field here is built on wrapping primitives, and every post-process
//      indexes modulo the size, so the left edge is the right edge by construction.
//   2. They must match the palette. Each is derived from TERRAIN_COLOR in
//      src/ui/theme.ts — the same source the flat board reads — so the textured and
//      untextured boards cannot drift apart.
//   3. They must be reproducible. No API key, no network, no spend, no per-run
//      variation: the same seed gives the same output on any machine.
//
// ── How a material is built ──────────────────────────────────────────────────
// A material is a HEIGHT FIELD plus a layered albedo, never a colour function.
// That split is where the realism comes from. Describing shape first and then
// lighting it — normals from the gradient, real cast shadows, horizon occlusion —
// is what makes crowns look domed, ridges throw shade into the valley behind them,
// mortar sit in a groove and dune slip faces read as slip faces.
//
// The field is built as a whole array rather than sampled per pixel, so PROCESSES
// can run on it: hydraulic erosion cuts drainage channels, thermal erosion slumps
// anything past the angle of repose. Those two do more for realism than any amount
// of noise-stacking, because they are what actually shapes ground.
//
// ── Output ───────────────────────────────────────────────────────────────────
//   <name>.webp    albedo, UNLIT — colour only, for the GL board to light itself
//   <name>-s.webp  RG normal, B occlusion (AO x cast shadow), A roughness
//   <name>-p.webp  prelit composite, for the CSS board, which cannot relight
//
// Occlusion folds the cast shadow in because the board's light is fixed relative
// to the board, so a baked shadow term stays correct — while the normal map still
// buys view-dependent specular as the camera moves, which baked light cannot.

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { TERRAIN_COLOR } from '../src/ui/theme';
import type { Terrain } from '../src/engine';

// ---------------------------------------------------------------------------
// Colour + scalar helpers. theme.ts owns the palette; this owns the maths.
// ---------------------------------------------------------------------------

type RGB = [number, number, number];

function parseHex(hex: string): RGB {
  const n = Number.parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

function mix(a: RGB, b: RGB, t: number): RGB {
  return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
}

/** Multiply toward black (f < 1) or toward white (f > 1), clamped. */
function shade(c: RGB, f: number): RGB {
  return [Math.min(255, c[0] * f), Math.min(255, c[1] * f), Math.min(255, c[2] * f)];
}

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);

function smoothstep(edge0: number, edge1: number, x: number): number {
  const t = clamp01((x - edge0) / (edge1 - edge0));
  return t * t * (3 - 2 * t);
}

const frac = (v: number) => v - Math.floor(v);

const TAU = Math.PI * 2;

// ---------------------------------------------------------------------------
// Style
//
// One knob set, chosen on the command line, that every material reads. Stylised
// sharpens the masks and holds back high-frequency energy so a terrain still reads
// as itself at 92px on the board; photoreal keeps the fine detail and softens the
// masks, which looks better close up and busier far away. The toggle exists
// because that trade is a judgement call, not a fact.
// ---------------------------------------------------------------------------

interface StyleParams {
  /** Amplitude multiplier on every detail octave — the third and beyond. */
  detail: number;
  /** Fractal octaves added to (or taken off) each material's own count. */
  octaves: number;
  /** >1 sharpens every mask edge, so features separate instead of blending. */
  contrast: number;
  /** Multiplier on ambient occlusion and cast shadow strength. */
  shade: number;
  /** Per-pixel colour noise — the thing that reads as "not computer-generated". */
  grain: number;
  /**
   * High-frequency relief added to EVERY material's height before it is shaded.
   * Gives photoreal its surface tooth.
   */
  micro: number;
  /** Colour saturation. Stylised pushes it; photoreal pulls toward natural. */
  sat: number;
  /**
   * Multiplier on every base noise period — the size of the features themselves.
   *
   * ⚠ The ONLY parameter here that survives being looked at from across the board,
   * and the reason the first two attempts at this table failed. Everything else —
   * micro-relief, extra octaves, grain — lives in the high frequencies, and a 92px
   * tile samples a 1024 texture around mip 3, so mipmapping averages exactly that
   * away. Measured, the two styles came out 1.4% apart on the GL board while their
   * source files differed by 6%. Feature SIZE is low-frequency, so it survives.
   *
   * Rounded to an integer wherever it is applied: a fractional period breaks the
   * wrapping lattice and the tile stops tiling.
   */
  scale: number;
  /** Overall lift/gain on the final colour — stylised is brighter and punchier. */
  tone: number;
}

const STYLES: Record<string, StyleParams> = {
  // Fewer, cleaner, more separated features and a flatter light — reads as itself
  // at 92px on the board.
  stylised: {
    detail: 0.3, octaves: -1, contrast: 1.7, shade: 0.62, grain: 0.012, micro: 0.003,
    sat: 1.35, scale: 0.6, tone: 1.1,
  },
  // Every octave at full strength, real surface tooth, deeper shading, muted
  // colour. Better close up; busier from across the board.
  photoreal: {
    detail: 1.15, octaves: 2, contrast: 0.82, shade: 1.4, grain: 0.1, micro: 0.055,
    sat: 0.82, scale: 1.7, tone: 0.9,
  },
};

let STYLE: StyleParams = STYLES['stylised']!;

/**
 * How much the material being rendered follows the STYLE at all, 0..1.
 *
 * Set by `render` from `Material.styleFollow`, and read wherever `STYLE` is —
 * feature scale, octaves, detail amplitude, grain, saturation and tone.
 *
 * Some materials should barely move between art directions. Water is water: the
 * photoreal style's finer feature scale and octave boost turned the sea into
 * crumpled wet rock, and its desaturation left it grey. Rock and earth take the
 * full amount, which is where the two styles are supposed to diverge.
 */
let STYLE_FOLLOW = 1;

/** Push a 0..1 mask away from its midpoint, by however much the style asks. */
function sharpen(t: number): number {
  const k = STYLE.contrast;
  if (k === 1) return t;
  return clamp01(0.5 + (t - 0.5) * k);
}

// ---------------------------------------------------------------------------
// Wrapping noise
//
// Every generator below indexes its lattice MODULO the period, so sampling at
// u = 1 hits the same lattice as u = 0 and the result tiles with no seam. Every
// octave uses a period that is an integer multiple of the base, which keeps that
// true once octaves are summed — a fractal built on the usual non-integer 2.017
// lacunarity would tile visibly wrongly here.
// ---------------------------------------------------------------------------

function hash2(ix: number, iy: number, seed: number): number {
  let h = (Math.imul(ix, 374761393) + Math.imul(iy, 668265263) + Math.imul(seed, 1274126177)) | 0;
  h = (h ^ (h >>> 13)) | 0;
  h = Math.imul(h, 1274126177) | 0;
  h = (h ^ (h >>> 16)) >>> 0;
  return h / 4294967296;
}

const wrap = (i: number, n: number) => ((i % n) + n) % n;

/**
 * A material's requested period, resized by the style.
 *
 * Integer, always: the wrapping lattices index modulo the period, so a fractional
 * one stops the texture tiling. Clamped to 1 so a heavily downscaled style cannot
 * collapse a field to a constant.
 */
const scaled = (period: number) => Math.max(1, Math.round(period * lerp(1, STYLE.scale, STYLE_FOLLOW)));

/** Perlin's quintic fade — zero first AND second derivative at the lattice. */
const fade = (t: number) => t * t * t * (t * (t * 6 - 15) + 10);

/**
 * Gradient (Perlin) noise, wrapping, in 0..1.
 *
 * Replaces the value noise this generator started on. Value noise interpolates
 * hashed VALUES at the lattice, which leaves its extrema pinned to lattice points
 * and reads as soft blobs on a grid; gradient noise interpolates hashed SLOPES, so
 * features fall between lattice points and the result is isotropic. Everything
 * built on top — the fractals, the warps — inherits that.
 */
function gnoiseRect(u: number, v: number, pu: number, pv: number, seed: number): number {
  const fx = u * pu;
  const fy = v * pv;
  const x0 = Math.floor(fx);
  const y0 = Math.floor(fy);
  const tx = fx - x0;
  const ty = fy - y0;
  const dot = (ix: number, iy: number, dx: number, dy: number) => {
    const a = hash2(wrap(ix, pu), wrap(iy, pv), seed) * TAU;
    return Math.cos(a) * dx + Math.sin(a) * dy;
  };
  const n00 = dot(x0, y0, tx, ty);
  const n10 = dot(x0 + 1, y0, tx - 1, ty);
  const n01 = dot(x0, y0 + 1, tx, ty - 1);
  const n11 = dot(x0 + 1, y0 + 1, tx - 1, ty - 1);
  const fx2 = fade(tx);
  const fy2 = fade(ty);
  const n = lerp(lerp(n00, n10, fx2), lerp(n01, n11, fx2), fy2);
  // 2D Perlin spans +/- sqrt(2)/2; rescale to 0..1.
  return clamp01(n * 0.7071 + 0.5);
}

const gnoise = (u: number, v: number, period: number, seed: number) =>
  gnoiseRect(u, v, scaled(period), scaled(period), seed);

/**
 * Fractal sum on a STRETCHED lattice — grain that runs one way.
 *
 * Directional detail cannot come from offsetting the sample position by a flow
 * field: that distorts the noise into whorls, and grass built that way came out
 * looking like a fingerprint. Stretching the lattice instead keeps the noise
 * itself intact and simply makes its features longer on one axis. Both periods
 * stay integers, so it still tiles.
 */
function fbmRect(u: number, v: number, pu: number, pv: number, octaves: number, seed: number): number {
  let sum = 0;
  let amp = 1;
  let norm = 0;
  for (let o = 0; o < Math.max(1, octaves + STYLE.octaves); o++) {
    sum += amp * gnoiseRect(u, v, scaled(pu) * 2 ** o, scaled(pv) * 2 ** o, seed + o * 101);
    norm += amp;
    amp *= 0.5;
  }
  return sum / norm;
}

/** Fractal sum. `period` doubles per octave so every octave still wraps. */
function fbm(u: number, v: number, period: number, octaves: number, seed: number): number {
  let sum = 0;
  let amp = 1;
  let norm = 0;
  const n = Math.max(1, octaves + Math.round(STYLE.octaves * STYLE_FOLLOW));
  for (let o = 0; o < n; o++) {
    // Everything past the first two octaves is DETAIL, and the style scales all of
    // it. Scaling only the last octave (the first attempt) touched a few percent
    // of the field and the two styles were indistinguishable.
    const styled = o >= 2 ? amp * lerp(1, STYLE.detail, STYLE_FOLLOW) : amp;
    sum += styled * gnoiseRect(u, v, scaled(period) * 2 ** o, scaled(period) * 2 ** o, seed + o * 101);
    norm += styled;
    amp *= 0.5;
  }
  return sum / norm;
}

/** Ridged fractal — the sharp crease that makes rock read as rock. */
function ridged(u: number, v: number, period: number, octaves: number, seed: number): number {
  let sum = 0;
  let amp = 1;
  let norm = 0;
  for (let o = 0; o < Math.max(1, octaves + Math.round(STYLE.octaves * STYLE_FOLLOW)); o++) {
    const n = gnoiseRect(u, v, scaled(period) * 2 ** o, scaled(period) * 2 ** o, seed + o * 101);
    sum += amp * (1 - Math.abs(2 * n - 1));
    norm += amp;
    amp *= 0.5;
  }
  return sum / norm;
}

/** Turbulence — |noise| summed. The classic marble / weathering field. */
function turbulence(u: number, v: number, period: number, octaves: number, seed: number): number {
  let sum = 0;
  let amp = 1;
  let norm = 0;
  for (let o = 0; o < Math.max(1, octaves + Math.round(STYLE.octaves * STYLE_FOLLOW)); o++) {
    sum += amp * Math.abs(2 * gnoiseRect(u, v, scaled(period) * 2 ** o, scaled(period) * 2 ** o, seed + o * 101) - 1);
    norm += amp;
    amp *= 0.5;
  }
  return sum / norm;
}

/** What a cellular lookup yields: the two nearest feature distances and a cell id. */
interface Cell {
  /** Distance to the nearest feature point, in cell widths. Domes, stones, crowns. */
  f1: number;
  /** Distance to the second nearest. `f2 - f1` is the cell BORDER — cracks, mortar. */
  f2: number;
  /** Stable 0..1 hash of the owning cell. Per-block tint, per-crown hue, per-stone size. */
  id: number;
}

/**
 * Wrapping cellular (Worley) noise, on a rectangular lattice.
 *
 * This is what the first version of this generator was missing, and it is the
 * reason so much of it had to be faked: masonry was a `frac()` grid, flagstones
 * were the same grid again, canopy was smoothed fbm, and pebbles were a bespoke
 * lattice scan. All of those are cellular noise, and having it once means each of
 * them can be the real thing — irregular, individually identifiable, with borders
 * that are actual borders rather than drawn lines.
 */
function worleyRect(u: number, v: number, pu0: number, pv0: number, seed: number, jitter = 0.9): Cell {
  const pu = scaled(pu0);
  const pv = scaled(pv0);
  const fx = u * pu;
  const fy = v * pv;
  const gx = Math.floor(fx);
  const gy = Math.floor(fy);
  let f1 = Infinity;
  let f2 = Infinity;
  let id = 0;
  for (let dy = -1; dy <= 1; dy++) {
    for (let dx = -1; dx <= 1; dx++) {
      const cx = gx + dx;
      const cy = gy + dy;
      const wx = wrap(cx, pu);
      const wy = wrap(cy, pv);
      const px = cx + 0.5 + (hash2(wx, wy, seed) - 0.5) * jitter;
      const py = cy + 0.5 + (hash2(wx, wy, seed + 7) - 0.5) * jitter;
      const d = Math.hypot(fx - px, fy - py);
      if (d < f1) {
        f2 = f1;
        f1 = d;
        id = hash2(wx, wy, seed + 31);
      } else if (d < f2) {
        f2 = d;
      }
    }
  }
  return { f1, f2, id };
}

const worley = (u: number, v: number, period: number, seed: number, jitter = 0.9): Cell =>
  worleyRect(u, v, period, period, seed, jitter);

/**
 * Two-level domain warp — sample the field at a position the field itself chose.
 *
 * Tiling survives because every warp offset comes from noise that is already
 * periodic with period 1: `f(u + w(u))` at u = 1 reads the same sample as at u = 0.
 * This is the single cheapest way to stop a fractal looking like a fractal.
 */
function warp2(u: number, v: number, period: number, seed: number, strength: number): [number, number] {
  const qx = fbm(u, v, period, 3, seed) - 0.5;
  const qy = fbm(u, v, period, 3, seed + 101) - 0.5;
  const rx = fbm(u + qx * strength, v + qy * strength, period, 3, seed + 211) - 0.5;
  const ry = fbm(u + qx * strength, v + qy * strength, period, 3, seed + 307) - 0.5;
  return [u + rx * strength, v + ry * strength];
}

/**
 * A unit direction that varies smoothly across the tile — the gradient of a slow
 * noise, turned ninety degrees so the field flows AROUND its features rather than
 * out of them. Wind streaks on sand, weathering running down a wall, the lie of
 * grass all follow it.
 */
function flowDir(u: number, v: number, period: number, seed: number): [number, number] {
  const e = 0.004;
  const gx = gnoise(u + e, v, period, seed) - gnoise(u - e, v, period, seed);
  const gy = gnoise(u, v + e, period, seed) - gnoise(u, v - e, period, seed);
  const len = Math.hypot(gx, gy) || 1;
  return [-gy / len, gx / len];
}

/** Project a point onto a flow line — the coordinate streaks run along. */
function flowCoord(u: number, v: number, period: number, seed: number, scale: number): number {
  const [dx, dy] = flowDir(u, v, period, seed);
  return (u * dx + v * dy) * scale;
}

/** One block of a coursed lattice. */
interface Brick {
  /** 0 in the joint, 1 in the middle of a face. */
  face: number;
  /** Stable 0..1 hash of this block. */
  id: number;
  /** Position within the block, 0..1 on each axis. */
  bx: number;
  by: number;
}

/**
 * Coursed masonry — rows of blocks, each row with its own block count and phase.
 *
 * Worley was the wrong tool here and it showed: cellular noise makes POLYGONS, so
 * both the wall and the flagstone floor came out as crazy paving. Masonry is laid
 * in courses, and what makes it look irregular is that no two courses share a block
 * width or a starting offset — not that the blocks stop being rectangles.
 *
 * Tiling holds because the column count is an integer (so `frac(u * cols + phase)`
 * repeats at u = 1 whatever the phase) and the row index wraps.
 */
function brick(u: number, v: number, rows: number, seed: number, joint: number): Brick {
  const row = wrap(Math.floor(v * rows), rows);
  const cols = 3 + Math.floor(hash2(row, 0, seed) * 3); // 3..5 blocks per course
  const phase = hash2(row, 1, seed + 5);
  const bx = frac(u * cols + phase);
  const by = frac(v * rows);
  const col = wrap(Math.floor(u * cols + phase), cols);
  // Distance to the nearest joint, converted to texture units so a horizontal and
  // a vertical joint come out the same physical width.
  const fx = Math.min(bx, 1 - bx) / cols;
  const fy = Math.min(by, 1 - by) / rows;
  // Chipped, not machined: the joint wanders by a little noise before it is cut.
  const chip = (fbm(u, v, 28, 3, seed + 17) - 0.5) * joint * 0.7;
  return {
    face: Math.min(smoothstep(0, joint + chip, fx), smoothstep(0, joint + chip, fy)),
    id: hash2(col, row, seed + 11),
    bx,
    by,
  };
}

// ---------------------------------------------------------------------------
// Field operations
//
// The height field is an array, so it can be processed. This is the part that no
// amount of extra noise substitutes for: erosion is what puts drainage channels in
// a mountain and a slip face on a dune, and both are shapes noise does not make.
//
// Every one of these wraps. A process that indexes off the edge without a modulo
// is the most likely way to lose the tiling, so `idx` is the only accessor used.
// ---------------------------------------------------------------------------

function fieldFrom(size: number, fn: (u: number, v: number) => number): Float32Array {
  const H = new Float32Array(size * size);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      // Sample at the pixel CENTRE. Sampling at the corner makes the last column
      // read u = (size-1)/size rather than wrapping cleanly, which shows up as a
      // one-pixel seam once the texture repeats.
      H[y * size + x] = fn((x + 0.5) / size, (y + 0.5) / size);
    }
  }
  return H;
}

const idx = (x: number, y: number, size: number) => wrap(y, size) * size + wrap(x, size);

function normalizeField(H: Float32Array): Float32Array {
  let lo = Infinity;
  let hi = -Infinity;
  for (let i = 0; i < H.length; i++) {
    const v = H[i]!;
    if (v < lo) lo = v;
    if (v > hi) hi = v;
  }
  const d = hi - lo || 1;
  for (let i = 0; i < H.length; i++) H[i] = (H[i]! - lo) / d;
  return H;
}

/** Box blur with wrapping, separable. Also the base of the cavity term. */
function blurWrap(src: Float32Array, size: number, radius: number): Float32Array {
  const tmp = new Float32Array(size * size);
  const out = new Float32Array(size * size);
  const w = radius * 2 + 1;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let sum = 0;
      for (let k = -radius; k <= radius; k++) sum += src[y * size + wrap(x + k, size)]!;
      tmp[y * size + x] = sum / w;
    }
  }
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let sum = 0;
      for (let k = -radius; k <= radius; k++) sum += tmp[wrap(y + k, size) * size + x]!;
      out[y * size + x] = sum / w;
    }
  }
  return out;
}

const NB4: readonly [number, number][] = [[1, 0], [-1, 0], [0, 1], [0, -1]];

/**
 * Thermal erosion — material slumps wherever the slope exceeds the angle of repose.
 *
 * Cheap, and it does two jobs no noise function does: it piles scree at the foot of
 * anything steep, and it produces the sharp SLIP FACE that separates a sand dune
 * from a sine wave. Sand has a low repose angle, rock a high one, which is the
 * whole difference between how the two settle.
 */
function thermalErode(H: Float32Array, size: number, iterations: number, talus: number, rate = 0.5): Float32Array {
  const delta = new Float32Array(size * size);
  for (let it = 0; it < iterations; it++) {
    delta.fill(0);
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const h = H[y * size + x]!;
        let total = 0;
        let peak = 0;
        for (const [dx, dy] of NB4) {
          const dh = h - H[idx(x + dx, y + dy, size)]!;
          if (dh > talus) {
            total += dh - talus;
            if (dh > peak) peak = dh;
          }
        }
        if (total <= 0) continue;
        const move = rate * (peak - talus) * 0.5;
        delta[y * size + x] = delta[y * size + x]! - move;
        for (const [dx, dy] of NB4) {
          const dh = h - H[idx(x + dx, y + dy, size)]!;
          if (dh > talus) {
            const j = idx(x + dx, y + dy, size);
            delta[j] = delta[j]! + (move * (dh - talus)) / total;
          }
        }
      }
    }
    for (let i = 0; i < H.length; i++) H[i] = H[i]! + delta[i]!;
  }
  return H;
}

/** Bilinear sample of a wrapping field, and its gradient, at fractional coords. */
function sampleField(H: Float32Array, size: number, x: number, y: number): { h: number; gx: number; gy: number } {
  const x0 = Math.floor(x);
  const y0 = Math.floor(y);
  const tx = x - x0;
  const ty = y - y0;
  const h00 = H[idx(x0, y0, size)]!;
  const h10 = H[idx(x0 + 1, y0, size)]!;
  const h01 = H[idx(x0, y0 + 1, size)]!;
  const h11 = H[idx(x0 + 1, y0 + 1, size)]!;
  return {
    h: lerp(lerp(h00, h10, tx), lerp(h01, h11, tx), ty),
    gx: lerp(h10 - h00, h11 - h01, ty),
    gy: lerp(h01 - h00, h11 - h10, tx),
  };
}

/**
 * Hydraulic erosion — droplets that carry sediment downhill.
 *
 * The single biggest realism gain in this file. Ridged noise gives you ridges but
 * no DRAINAGE: real high ground is cut by branching channels that converge, and
 * that structure is what the eye reads as a mountain rather than as crumpled paper.
 * A droplet gains speed descending, erodes above its carrying capacity, and drops
 * its load when the ground flattens — which deposits fans exactly where a river
 * leaves the hills.
 *
 * Deposits and erodes through a small brush rather than a single cell, or every
 * droplet digs a one-pixel needle and the field turns to noise.
 */
function hydraulicErode(H: Float32Array, size: number, droplets: number, seed: number): Float32Array {
  const inertia = 0.06;
  const capacityK = 5;
  const minSlope = 0.002;
  const erodeRate = 0.28;
  const depositRate = 0.28;
  const evaporate = 0.02;
  const gravity = 6;
  const maxSteps = 42;
  let rng = seed >>> 0;
  const rand = () => {
    rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0;
    return rng / 4294967296;
  };

  for (let d = 0; d < droplets; d++) {
    let x = rand() * size;
    let y = rand() * size;
    let dx = 0;
    let dy = 0;
    let speed = 1;
    let water = 1;
    let sediment = 0;

    for (let step = 0; step < maxSteps; step++) {
      const s = sampleField(H, size, x, y);
      dx = dx * inertia - s.gx * (1 - inertia);
      dy = dy * inertia - s.gy * (1 - inertia);
      const len = Math.hypot(dx, dy);
      if (len < 1e-6) break;
      dx /= len;
      dy /= len;
      const nx = x + dx;
      const ny = y + dy;
      const dh = sampleField(H, size, nx, ny).h - s.h;

      const capacity = Math.max(-dh, minSlope) * speed * water * capacityK;
      if (sediment > capacity || dh > 0) {
        // Uphill, or over capacity: drop material. Filling a pit takes only as
        // much as the pit holds, which is what stops droplets building towers.
        const drop = dh > 0 ? Math.min(dh, sediment) : (sediment - capacity) * depositRate;
        sediment -= drop;
        deposit(H, size, x, y, drop);
      } else {
        const take = Math.min((capacity - sediment) * erodeRate, -dh);
        sediment += take;
        deposit(H, size, x, y, -take);
      }

      speed = Math.sqrt(Math.max(0, speed * speed - dh * gravity));
      water *= 1 - evaporate;
      x = nx;
      y = ny;
      if (water < 0.01) break;
    }
  }
  return H;
}

/** Spread a change over a 3x3 brush so droplets carve valleys, not needles. */
function deposit(H: Float32Array, size: number, x: number, y: number, amount: number): void {
  const x0 = Math.floor(x);
  const y0 = Math.floor(y);
  let total = 0;
  const w: number[] = [];
  for (let j = -1; j <= 1; j++) {
    for (let i = -1; i <= 1; i++) {
      const k = Math.max(0, 1.5 - Math.hypot(x0 + i + 0.5 - x, y0 + j + 0.5 - y));
      w.push(k);
      total += k;
    }
  }
  if (total <= 0) return;
  let n = 0;
  for (let j = -1; j <= 1; j++) {
    for (let i = -1; i <= 1; i++) {
      const k = idx(x0 + i, y0 + j, size);
      H[k] = H[k]! + (amount * w[n]!) / total;
      n += 1;
    }
  }
}

/** Quantise into benches — strata on rock, courses on built stone. */
function terrace(H: Float32Array, steps: number, sharpness: number): Float32Array {
  for (let i = 0; i < H.length; i++) {
    const t = H[i]! * steps;
    const f = Math.floor(t);
    const r = t - f;
    H[i] = (f + smoothstep(0, 1, r) ** sharpness) / steps;
  }
  return H;
}

// ---------------------------------------------------------------------------
// The nine materials
//
// Each is a field plus a LAYERED albedo — sub-materials selected by the surface
// itself, not by (u, v) alone. That is the difference between "two greens mixed by
// height" and a forest whose gaps show litter, whose crowns each have their own
// hue, and whose undergrowth fills the space between.
// ---------------------------------------------------------------------------

/** What the shading pass knows about a pixel by the time albedo is asked for. */
interface Surface {
  /** Height, 0..1. */
  h: number;
  /** |gradient|, roughly 0..1 after scaling. Flat ground is 0. */
  slope: number;
  /** Positive in hollows, negative on ridges. */
  curvature: number;
  /** Ambient occlusion, 1 = open sky. */
  ao: number;
  /** 1 = lit, 0 = in the shadow of something else. */
  shadow: number;
}

interface Material {
  /** Build the whole height field, post-processes included. */
  field: (size: number) => Float32Array;
  /** Colour before any light touches it. */
  albedo: (u: number, v: number, s: Surface, base: RGB) => RGB;
  /** Vertical exaggeration when normals are derived. Higher = deeper relief. */
  relief: number;
  /** Specular strength, 0 = fully matte. */
  gloss: number;
  /** Tightness of the highlight. Larger = smaller, harder glint. */
  shine?: number;
  /** Multiplier on the occlusion term. */
  ao?: number;
  /**
   * Darkest the combined occlusion and shadow may go.
   *
   * Without it the sharp height step at a mortar joint occludes to nearly zero and
   * every wall and floor came out as black chasms between pale stones. Real joints
   * are dark, not absent.
   */
  aoFloor?: number;
  /** Light the surface returns regardless of angle. Shadow swallows its own. */
  ambient?: number;
  /** 0 = mirror, 1 = chalk. May vary per pixel. */
  rough?: (u: number, v: number, s: Surface) => number;
  /**
   * How much of the style's global micro-relief this material takes, 0..1.
   *
   * ⚠ Water needs almost none. The photoreal style adds surface tooth to every
   * material alike, which is right for earth and rock and completely wrong for a
   * liquid — the sea came out as crumpled wet foil, with a normal map full of
   * high-frequency noise where it should have been a smooth swell.
   */
  micro?: number;
  /**
   * How much this material follows the style, 0..1. Low means "look the same in
   * both art directions" — right for anything whose identity does not depend on
   * one, water above all.
   */
  styleFollow?: number;
}

/** Scale a raw gradient magnitude into a comfortable 0..1 slope. */
const slopeOf = (s: Surface) => clamp01(s.slope);

const MATERIALS: Record<Terrain, Material> = {
  // Grey brick paving. Most of the board is this, so it has to hold up without ever
  // asking to be looked at: small pavers laid in courses, joints that read as joints
  // rather than as cracks, and enough per-block variation that forty tiles of it do
  // not flatten into one slab.
  //
  // Built from the same brick() primitive as Wall, at a finer course count — this is
  // a floor being walked on, not a face catching raking light, so the relief is lower
  // and the wear lands on the crowns of the blocks rather than running down them.
  Normal: {
    relief: 2.6,
    gloss: 0.05,
    shine: 20,
    ao: 0.8,
    // ⚠ Needed for the same reason Wall needs one: without a floor, the height step
    // at a joint occludes to nearly zero and every joint renders as a black chasm.
    // 0.7, well above Wall's 0.4: a floor is lit from above, so its joints catch
    // far more sky than a wall's do. At 0.45 they still rendered as black slots.
    aoFloor: 0.7,
    // aoFloor alone was not enough — in the PRELIT map the joints are also fully
    // cast-shadowed, and there `ambient` is the floor, not aoFloor (see the `lit`
    // term in render()). 0.5 is what stops them reading as slots cut in the tile.
    ambient: 0.5,
    rough: () => 0.82,
    field: (size) =>
      fieldFrom(size, (u, v) => {
        const b = brick(u, v, 11, 331, 0.011);
        // Each paver bows very slightly, settles a little proud or low of its
        // neighbours, and roughly one in seven has a corner knocked off.
        const bow = (1 - Math.hypot(b.bx - 0.5, b.by - 0.5) * 1.3) * 0.07;
        const sunk = (b.id - 0.5) * 0.05;
        const chip = b.id > 0.86 ? smoothstep(0.3, 0.85, Math.hypot(b.bx - b.id, b.by - 0.5)) * 0.16 : 0;
        // Tooth on the faces only — the joints are filled, not abraded.
        const wear = fbm(u, v, 44, 3, 337) * 0.07;
        return 0.2 + b.face * (0.42 + bow + sunk - chip) + wear * b.face;
      }),
    albedo: (u, v, s, base) => {
      const b = brick(u, v, 11, 331, 0.011);
      // Every constant here is neutral. The whole point of the surface is that it
      // reads as grey stone, so nothing is allowed to pull it toward a hue.
      // Darker than the pavers by COLOUR, not only by occlusion — the joints have
      // to survive the aoFloor that keeps them from going black.
      const mortar = shade(mix(base, [84, 84, 90], 0.58), 0.78);
      const stone = shade(mix(base, [148, 148, 154], 0.4), 0.86 + b.id * 0.34);
      let c = mix(mortar, stone, b.face);
      // Per-paver drift between a warmer and a cooler grey, so a field of them is
      // not one value at forty brightnesses.
      c = mix(c, mix(c, [120, 122, 130], 0.5), turbulence(u, v, 6, 3, 341) * 0.18);
      // Grime collects in the joints, and in whatever the pavers have dished into.
      const grime = clamp01(s.curvature * 2.2) * (1 - b.face * 0.65);
      c = mix(c, shade(c, 0.7), clamp01(grime) * 0.5);
      // Foot polish on the crowns of the blocks, where the wear actually happens.
      const polish = b.face * smoothstep(0.45, 0.95, s.h) * (1 - slopeOf(s));
      c = mix(c, shade(c, 1.14), polish * 0.3);
      // Chipped corners show lighter, unweathered stone.
      const chip = b.id > 0.86 ? smoothstep(0.3, 0.85, Math.hypot(b.bx - b.id, b.by - 0.5)) : 0;
      return mix(c, shade(c, 1.2), chip * 0.4);
    },
  },

  // Canopy seen from above. One crown per cell, each with its own size, height and
  // hue; the gaps between them fall to litter and go dark. The occlusion in those
  // gaps is what sells it — a forest is mostly the shadow between the trees.
  Forest: {
    relief: 3.6,
    gloss: 0.05,
    ao: 1.7,
    rough: () => 0.95,
    field: (size) =>
      normalizeField(
        fieldFrom(size, (u, v) => {
          // Warped enough to ragged the crown outlines, and no more. At 0.42 the
          // cells folded into each other and the canopy came out as curled kale.
          const [wu, wv] = warp2(u, v, 6, 53, 0.14);
          const crown = worley(wu, wv, 5, 59, 1);
          const r = 0.44 + crown.id * 0.28;
          // A softer profile than a sphere, so crowns read as foliage rather than
          // as polished balls.
          const dome = crown.f1 < r ? (1 - (crown.f1 / r) ** 1.7) ** 0.8 : 0;
          const [uu, uv2] = warp2(u + 0.31, v + 0.17, 9, 61, 0.12);
          const under = worley(uu, uv2, 11, 63, 1);
          const ru = 0.4 + under.id * 0.22;
          const dome2 = under.f1 < ru ? (1 - (under.f1 / ru) ** 1.7) ** 0.8 : 0;
          const leaf = fbm(u, v, 30, 3, 67);
          return dome * 0.58 + dome2 * 0.22 + leaf * 0.14;
        }),
      ),
    albedo: (u, v, s, base) => {
      const [wu, wv] = warp2(u, v, 6, 53, 0.14);
      const crown = worley(wu, wv, 5, 59, 1);
      const litter = shade(mix(base, [72, 58, 36], 0.55), 0.7);
      const shadeLeaf = shade(base, 0.66);
      const litLeaf = mix(base, [188, 216, 124], 0.52);
      // Per-crown species drift: neighbouring trees are not the same green.
      const species = crown.id;
      const canopy = mix(shadeLeaf, litLeaf, smoothstep(0.35, 0.95, s.h));
      const tinted = mix(canopy, mix(canopy, [148, 176, 84], 0.55), species * 0.5);
      const c = mix(litter, tinted, sharpen(smoothstep(0.1, 0.42, s.h)));
      // Leaf speckle, strongest on the lit tops.
      return shade(c, 1 + (fbm(u, v, 70, 2, 71) - 0.5) * 0.22 * s.h);
    },
  },

  // Eroded rock. The ridged base is only the starting point — the droplets cut the
  // drainage, and the thermal pass piles the debris at the bottom of what they cut.
  Mountain: {
    relief: 4.4,
    gloss: 0.07,
    shine: 26,
    ao: 1.05,
    rough: (u, v, s) => 0.62 + (1 - slopeOf(s)) * 0.2,
    field: (size) => {
      const H = fieldFrom(size, (u, v) => {
        // ⚠ LOW base frequency, and the large scale kept dominant. At period 4
        // with five octaves the erosion had nothing broad to cut into and carved
        // a mat of one-pixel worms instead of a ridge-and-valley system.
        const [wu, wv] = warp2(u, v, 3, 73, 0.22);
        const massif = ridged(wu, wv, 2, 3, 79) ** 1.15;
        const detail = ridged(u, v, 8, 3, 81);
        return massif * 0.82 + detail * 0.18;
      });
      // Fewer droplets, so channels converge into a few real drainages rather
      // than covering every square inch.
      hydraulicErode(H, size, Math.round(size * size * 0.06), 8123);
      thermalErode(H, size, 4, 0.02); // rock stands steep; talus is small
      return normalizeField(H);
    },
    albedo: (u, v, s, base) => {
      const [wu, wv] = warp2(u, v, 3, 73, 0.34);
      // Strata follow FOLDED rock, not the texture axes — banding on raw height
      // reads as contour lines on a map.
      const band = Math.sin((s.h * 8 + turbulence(wu, wv, 5, 3, 83) * 3) * TAU) * 0.5 + 0.5;
      // Keep the palette: pulling half-way to neutral grey drained the terrain
      // token out of the rock entirely.
      const dark = shade(mix(base, [92, 78, 62], 0.3), 0.74);
      const lit = mix(base, [236, 226, 208], 0.42);
      let c = mix(dark, lit, smoothstep(0.08, 0.86, s.h));
      c = mix(c, shade(c, 0.88), band * 0.2);
      // Scree collects where it can rest: low ground, shallow slope.
      const screeMask = sharpen((1 - slopeOf(s)) * (1 - smoothstep(0.2, 0.6, s.h)));
      const pebble = worley(u, v, 34, 89, 1).f1;
      const scree = shade(mix(base, [138, 126, 110], 0.5), 0.8 + (pebble < 0.3 ? 0.3 : 0));
      c = mix(c, scree, screeMask * 0.6);
      // Lichen in the hollows the water does not scour.
      const lichen = clamp01(s.curvature * 3) * (1 - screeMask);
      c = mix(c, mix(c, [126, 142, 92], 0.6), lichen * 0.35 * turbulence(u, v, 12, 3, 97));
      // Snow high AND flat, with a wind-scoured edge rather than a contour line.
      const snowMask = sharpen(smoothstep(0.72, 0.93, s.h) * (1 - smoothstep(0.25, 0.6, slopeOf(s))));
      const wind = fbm(u, v, 14, 3, 101);
      return mix(c, [242, 246, 250], clamp01(snowMask * (0.55 + wind * 0.6)));
    },
  },

  // Open water. Several wave trains rather than one, crests sharpened, foam carried
  // along the flow instead of thresholded, and light filaments in the shallows.
  Sea: {
    relief: 1.4,
    gloss: 0.55,
    shine: 46,
    ao: 0.25,
    ambient: 0.4,
    rough: () => 0.1,
    // Almost none of the global surface tooth, and almost none of the octave
    // boost: water is smooth, and taking the full amount of either turned it into
    // crumpled foil. The sea looks near-identical in both styles by design.
    micro: 0.06,
    styleFollow: 0.15,
    field: (size) =>
      normalizeField(
        fieldFrom(size, (u, v) => {
          const swell = fbm(u, v, 4, 3, 103);
          // Sharpened crests: |sin| raised to a power rounds the troughs and peaks
          // the tops, which is the shape water actually takes.
          const train = (fu: number, ph: number, amp: number) => {
            const w = Math.sin(fu * TAU + ph) * 0.5 + 0.5;
            return w ** 1.6 * amp;
          };
          // ⚠ Frequencies are per TILE, and a tile is one cell of a 7x7 board, not
          // an ocean. At four bands per tile the sea read as painted stripes on the
          // board however good the material looked at full resolution — open water
          // seen from a few metres up is many small ripples, not three big swells.
          const a = train(v * 9, swell * 3, 1);
          const b = train(u * 5 + v * 4, -swell * 2, 0.55);
          const c = train(u * 11 - v * 7, swell * 1.5, 0.28);
          // Chop stays gentle at every style. A liquid's fine structure is ripples
          // on a swell, not grain — letting `detail` drive it hard was half of what
          // made the photoreal sea read as rock.
          const chop = fbm(u, v, 22, 3, 107) * 0.09;
          return (a + b + c) / 1.7 + chop;
        }),
      ),
    albedo: (u, v, s, base) => {
      // Saturated, and a wide range between trough and crest. The photoreal style
      // desaturates by 0.82, which on an already-hazy blue left the sea grey.
      const deep = shade(mix(base, [26, 66, 130], 0.45), 0.92);
      const shallow = mix(base, [140, 206, 240], 0.5);
      let c = mix(deep, shallow, smoothstep(0.05, 0.98, s.h) ** 0.7);
      // Caustics: bright filaments where light focuses, cell borders on a warped
      // field. Strongest where the water is shallow.
      // Warped hard, or the cell lattice reads straight through as a honeycomb.
      const [cu, cv] = warp2(u, v, 5, 109, 0.5);
      const caustic = worley(cu, cv, 9, 113, 1);
      const fil = 1 - smoothstep(0, 0.07, caustic.f2 - caustic.f1);
      c = mix(c, mix(c, [214, 244, 255], 0.8), fil * smoothstep(0.45, 0.95, s.h) * 0.3);
      // Foam gathers along the crest lines and streaks with the flow, rather than
      // capping every wave at a threshold — that read as frost on a window.
      const streak = frac(flowCoord(u, v, 5, 127, 9) + fbm(u, v, 12, 3, 131));
      const foam = smoothstep(0.82, 1, s.h) * smoothstep(0.35, 0.85, streak);
      return mix(c, [232, 244, 250], foam * 0.55 * STYLE.detail);
    },
  },

  // Turf. Clumped tufts with their own heights and hues, blades lying along a flow
  // direction, and soil showing through wherever the cover thins.
  Grassland: {
    relief: 1.7,
    gloss: 0.04,
    ao: 0.65,
    rough: () => 0.92,
    field: (size) =>
      normalizeField(
        fieldFrom(size, (u, v) => {
          // ⚠ No per-tuft domes, and no flow-warped sampling. A hemisphere per
          // clump reads as gravel at 92px, and offsetting the sample position by
          // a flow field turned the grain into fingerprint whorls. Turf is a slow
          // swell, patchy clumping, and fine grain that leans one way.
          const swell = fbm(u, v, 4, 3, 137) * 0.6;
          const clump = fbm(u, v, 13, 3, 151) * 0.22;
          const blade = fbmRect(u, v, 104, 46, 2, 153) * 0.2;
          return swell + clump + blade;
        }),
      ),
    albedo: (u, v, s, base) => {
      const patch = fbm(u, v, 4, 3, 157);
      const dry = mix(base, [200, 190, 104], 0.55);
      const lush = mix(base, [88, 134, 56], 0.5);
      const soil = shade(mix(base, [118, 96, 62], 0.6), 0.72);
      const tuft = worley(u, v, 30, 139, 1);
      let c = mix(lush, dry, sharpen(smoothstep(0.32, 0.82, patch)));
      // Per-clump variation: no two tufts the same green.
      c = shade(c, 0.88 + tuft.id * 0.28);
      // Soil through the thinnest cover.
      c = mix(soil, c, sharpen(smoothstep(0.05, 0.35, s.h)));
      // A rare flower head, only in cells that draw the short straw.
      const flower = tuft.id > 0.965 && tuft.f1 < 0.2 ? smoothstep(0.2, 0.05, tuft.f1) : 0;
      c = mix(c, [232, 226, 168], flower * 0.7);
      return shade(c, 0.9 + s.h * 0.24);
    },
  },

  // Dunes. The asymmetry is the whole thing: a long windward slope and a short,
  // steep slip face. Thermal erosion at sand's low angle of repose builds that from
  // a symmetric start, which is exactly how it forms in the field.
  Desert: {
    relief: 2.6,
    gloss: 0.05,
    ao: 0.35,
    rough: () => 0.85,
    field: (size) => {
      const H = fieldFrom(size, (u, v) => {
        const drift = fbm(u, v, 3, 3, 163);
        const axis = u + v * 3 + drift * 0.7;
        // A skewed wave: rises slowly, falls fast. Erosion then sharpens the fall
        // into a true slip face.
        const t = frac(axis);
        const dune = t < 0.72 ? smoothstep(0, 0.72, t) : 1 - smoothstep(0.72, 1, t);
        return dune * 0.85 + fbm(u, v, 40, 3, 167) * 0.1;
      });
      thermalErode(H, size, 14, 0.006); // sand slumps easily — a low talus angle
      return normalizeField(H);
    },
    albedo: (u, v, s, base) => {
      const shadowed = shade(mix(base, [148, 112, 62], 0.42), 0.82);
      const crest = mix(base, [252, 240, 200], 0.55);
      let c = mix(shadowed, crest, clamp01(s.h * 0.85 + fbm(u, v, 8, 2, 173) * 0.2));
      // Ripples run ALONG the crest, and die on the slip face where sand is
      // avalanching rather than being combed by the wind.
      const ripple = Math.sin(flowCoord(u, v, 4, 179, 60) * TAU) * 0.5 + 0.5;
      c = shade(c, 1 + (ripple - 0.5) * 0.1 * (1 - smoothstep(0.25, 0.55, slopeOf(s))) * STYLE.detail);
      // Gravel blown clear in the troughs.
      const gravelMask = 1 - smoothstep(0.06, 0.3, s.h);
      const pebble = worley(u, v, 40, 181, 1).f1;
      const gravel = shade(mix(base, [124, 106, 84], 0.55), pebble < 0.3 ? 1.1 : 0.85);
      return mix(c, gravel, gravelMask * 0.45);
    },
  },

  // A place light does not reach. Low relief, high ambient, and veins that stay
  // bright through the shading — it should look like it is absorbing the light
  // rather than catching it.
  Shadow: {
    relief: 1.7,
    gloss: 0.16,
    shine: 14,
    ao: 0.85,
    ambient: 0.66,
    rough: () => 0.45,
    field: (size) =>
      normalizeField(
        fieldFrom(size, (u, v) => {
          // Wisps: several offset warps of the same field, which reads as depth
          // without any actual volume.
          const [a1, b1] = warp2(u, v, 3, 191, 0.4);
          const [a2, b2] = warp2(u + 0.13, v + 0.07, 5, 193, 0.26);
          return (
            turbulence(a1, b1, 4, 4, 197) * 0.55 +
            turbulence(a2, b2, 9, 3, 199) * 0.3 +
            fbm(u, v, 22, 3, 211) * 0.15
          );
        }),
      ),
    albedo: (u, v, s, base) => {
      const voidC = shade(mix(base, [20, 12, 32], 0.62), 0.48);
      const glow = mix(base, [182, 156, 232], 0.55);
      let c = mix(voidC, glow, sharpen(smoothstep(0.28, 0.86, s.h)) * 0.8);
      // Veins along cell borders, boosted enough to survive the shading pass.
      const [wu, wv] = warp2(u, v, 4, 223, 0.3);
      const vein = worley(wu, wv, 8, 227, 0.95);
      const seam = 1 - smoothstep(0, 0.08, vein.f2 - vein.f1);
      c = mix(c, [206, 178, 255], sharpen(seam) * 0.55);
      // Grazing-angle iridescence: only where the surface turns away.
      return mix(c, mix(c, [120, 190, 220], 0.5), slopeOf(s) * 0.22);
    },
  },

  // Built, not grown. Irregular flagstones — never a grid — with joints cut into
  // the height so they shadow themselves, moss where water sits, and a polished
  // track worn through the middle by everything that has walked it.
  Sanctuary: {
    relief: 4.2,
    gloss: 0.28,
    shine: 44,
    ao: 0.8,
    aoFloor: 0.45,
    rough: (u, v, s) => 0.35 + (1 - smoothstep(0.4, 0.9, s.h)) * 0.4,
    field: (size) =>
      fieldFrom(size, (u, v) => {
        const b = brick(u, v, 5, 233, 0.012);
        // Each slab sits at its own height and dishes very slightly in the middle,
        // the way a walked-on floor wears.
        const seat = 0.62 + b.id * 0.12;
        const dish = (1 - Math.hypot(b.bx - 0.5, b.by - 0.5) * 1.6) * 0.05;
        const wear = fbm(u, v, 36, 3, 239) * 0.05;
        return 0.24 + b.face * (seat - dish) + wear * b.face;
      }),
    albedo: (u, v, s, base) => {
      const b = brick(u, v, 5, 233, 0.012);
      // Marble veining, offset per slab so it never runs across a joint.
      const vein = turbulence(u * 1.4 + b.id * 3, v + b.id, 6, 4, 241);
      const pale = mix(base, [248, 242, 220], 0.5);
      const dim = shade(mix(base, [162, 148, 106], 0.4), 0.86);
      let c = mix(pale, dim, smoothstep(0.4, 0.8, vein) * 0.5);
      c = shade(c, 0.92 + b.id * 0.16);
      // Mortar, then moss in it — moss grows where water sits, so it keys off the
      // hollows rather than being painted along the lines.
      const mortar = 1 - b.face;
      c = mix(c, shade(base, 0.7), mortar * 0.7);
      const moss = mortar * clamp01(s.curvature * 2.5) * turbulence(u, v, 10, 3, 251);
      c = mix(c, mix(base, [96, 122, 64], 0.7), clamp01(moss) * 0.6);
      // The worn path: polished, lighter, and it ignores the joints.
      const path = smoothstep(0.35, 0.05, Math.abs(fbm(u, v, 3, 2, 257) - 0.5));
      return mix(c, shade(c, 1.12), path * 0.35);
    },
  },

  // Coursed masonry with variable block widths, so no two courses repeat. Streaks
  // run down from every joint the way water actually leaves a wall.
  Wall: {
    relief: 4.6,
    gloss: 0.1,
    shine: 22,
    ao: 0.85,
    aoFloor: 0.4,
    rough: () => 0.7,
    field: (size) =>
      fieldFrom(size, (u, v) => {
        const b = brick(u, v, 7, 269, 0.009);
        // Blocks bow out slightly, carry their own pitting, and one in five has a
        // corner spalled away.
        const bow = (1 - Math.hypot(b.bx - 0.5, b.by - 0.5) * 1.3) * 0.12;
        const pit = fbm(u, v, 50, 3, 271) * 0.1;
        const spall = b.id > 0.8 ? smoothstep(0.35, 0.9, Math.hypot(b.bx - b.id, b.by - 0.5)) * 0.2 : 0;
        return 0.18 + b.face * (0.6 + bow - spall) + pit * b.face;
      }),
    albedo: (u, v, s, base) => {
      const b = brick(u, v, 7, 269, 0.009);
      const mortar = shade(mix(base, [104, 104, 108], 0.3), 0.78);
      const stone = shade(mix(base, [132, 134, 142], 0.28), 0.86 + b.id * 0.4);
      let c = mix(mortar, stone, b.face);
      // Weathering runs DOWN from the joints. `v` is down in texture space, so
      // squashing v smears the noise vertically into a run-off streak.
      const streak = turbulence(u, v * 0.25, 10, 3, 277);
      c = mix(c, shade(c, 0.8), streak * 0.3);
      // Moss in the joints, where the wall stays damp.
      const moss = (1 - b.face) * clamp01(s.curvature * 2) * fbm(u, v, 9, 3, 281);
      c = mix(c, mix(base, [84, 108, 62], 0.65), clamp01(moss) * 0.55);
      // Spalled faces show lighter, unweathered stone.
      const spall = b.id > 0.8 ? smoothstep(0.35, 0.9, Math.hypot(b.bx - b.id, b.by - 0.5)) : 0;
      return mix(c, shade(c, 1.2), spall * 0.45);
    },
  },
};

// ---------------------------------------------------------------------------
// Shading
//
// Where the materials describe shape and colour, this turns them into a lit
// surface — and into the normal / occlusion / roughness map the GL board relights
// from.
// ---------------------------------------------------------------------------

/**
 * The sun, in texture space (u right, v down, h up).
 *
 * ⚠ Must stay in step with `LIGHT` in src/ui/SpikeGL.tsx, which lights the board
 * GEOMETRY. They previously agreed on azimuth but not elevation — 34° here against
 * 54° there — so baked relief and geometry relief were lit from different heights.
 *
 * The axes line up one-for-one, which is why the same three numbers serve both:
 * a tile's UVs put v = 0 on its south edge and v = 1 on its north, and image row 0
 * is v = 0, so texture +v IS world +y. Likewise +u is +x and +h is +z. That also
 * means the normal map needs no channel flip on the way into the shader.
 */
const LIGHT: [number, number, number] = (() => {
  const v: [number, number, number] = [-0.30, -0.50, 0.81];
  const n = Math.hypot(v[0], v[1], v[2]);
  return [v[0] / n, v[1] / n, v[2] / n];
})();

/**
 * Cast shadows: march toward the light and see whether anything gets in the way.
 *
 * The largest single gain in this pass. Local N·L alone tells you which way a face
 * points but never that a ridge is standing between this valley and the sun, and
 * that missing cue is most of why the old textures read flatter than their height
 * fields actually were.
 *
 * Heights are converted into PIXEL units first (`vScale`) so the ray's rise per
 * step is comparable with the field it is marching over.
 */
function castShadows(H: Float32Array, size: number, vScale: number, steps: number): Float32Array {
  const out = new Float32Array(size * size);
  const horiz = Math.hypot(LIGHT[0], LIGHT[1]) || 1e-6;
  const sx = LIGHT[0] / horiz;
  const sy = LIGHT[1] / horiz;
  const rise = (LIGHT[2] / horiz) * 1; // height gained per pixel stepped
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const h0 = H[y * size + x]! * vScale;
      let shadow = 1;
      for (let t = 1; t <= steps; t++) {
        const s = sampleField(H, size, x + sx * t, y + sy * t);
        const above = s.h * vScale - (h0 + rise * t);
        if (above > 0) {
          // Soft edge: how far the blocker rises above the ray decides how dark,
          // which gives a penumbra instead of a hard stencil.
          shadow = Math.min(shadow, clamp01(1 - above * 1.6));
          if (shadow <= 0) break;
        }
      }
      out[y * size + x] = shadow;
    }
  }
  return out;
}

/**
 * Horizon-based occlusion — how much of the sky each pixel can actually see.
 *
 * Replaces a blur-difference approximation that only noticed local dips. Marching
 * for the true horizon angle in several directions is what darkens the inside of a
 * crevice properly, and it is the reason the gaps between forest crowns read as
 * depth rather than as dark paint.
 */
function horizonAO(H: Float32Array, size: number, vScale: number, dirs: number, steps: number): Float32Array {
  const out = new Float32Array(size * size);
  const dx: number[] = [];
  const dy: number[] = [];
  for (let d = 0; d < dirs; d++) {
    const a = (d / dirs) * TAU;
    dx.push(Math.cos(a));
    dy.push(Math.sin(a));
  }
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const h0 = H[y * size + x]! * vScale;
      let open = 0;
      for (let d = 0; d < dirs; d++) {
        let maxTan = 0;
        for (let t = 1; t <= steps; t++) {
          const s = sampleField(H, size, x + dx[d]! * t, y + dy[d]! * t);
          const tan = (s.h * vScale - h0) / t;
          if (tan > maxTan) maxTan = tan;
        }
        // sin(atan(t)) without the trig.
        open += 1 - maxTan / Math.sqrt(1 + maxTan * maxTan);
      }
      out[y * size + x] = open / dirs;
    }
  }
  return out;
}

/** Nearest-neighbour-free bilinear upsample of a half-resolution wrapping field. */
function upsample(src: Float32Array, from: number, to: number): Float32Array {
  const out = new Float32Array(to * to);
  const k = from / to;
  for (let y = 0; y < to; y++) {
    for (let x = 0; x < to; x++) {
      out[y * to + x] = sampleField(src, from, (x + 0.5) * k - 0.5, (y + 0.5) * k - 0.5).h;
    }
  }
  return out;
}

/** Downsample a wrapping field by exactly two, for the half-res shading passes. */
function halve(src: Float32Array, size: number): Float32Array {
  const h = size >> 1;
  const out = new Float32Array(h * h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < h; x++) {
      out[y * h + x] =
        (src[idx(x * 2, y * 2, size)]! +
          src[idx(x * 2 + 1, y * 2, size)]! +
          src[idx(x * 2, y * 2 + 1, size)]! +
          src[idx(x * 2 + 1, y * 2 + 1, size)]!) /
        4;
    }
  }
  return out;
}

interface Maps {
  /** Unlit colour, at full size. */
  albedo: Buffer;
  /** RG normal, B occlusion, A roughness, at half size. */
  surface: Buffer;
  /** Lit composite, at half size. */
  prelit: Buffer;
}

function render(material: Material, base: RGB, size: number, fast: boolean): Maps {
  // Set BEFORE the field is built: the fractal sums read it while the material
  // runs, so assigning it afterwards would leave the height field unaffected.
  STYLE_FOLLOW = material.styleFollow ?? 1;
  const H = material.field(size);
  // Surface tooth, added to every material alike. Applied BEFORE the normalise so
  // it lands in the same units the field is already in, and before normals are
  // taken so it shows up in the map the board relights from.
  const micro = STYLE.micro * (material.micro ?? 1);
  if (micro > 0) {
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const u = (x + 0.5) / size;
        const v = (y + 0.5) / size;
        H[y * size + x] =
          H[y * size + x]! +
          (fbm(u, v, size >> 3, 3, 4243) - 0.5) * micro +
          (gnoise(u, v, size >> 1, 4271) - 0.5) * micro * 0.5;
      }
    }
  }
  normalizeField(H);
  const vScale = material.relief * size * 0.01;

  // Shadows and occlusion are low-frequency, so they are computed at half
  // resolution and upsampled. At 1024 the horizon march is otherwise minutes per
  // terrain for detail nobody can see.
  const half = size >> 1;
  const Hh = halve(H, size);
  const shadowHalf = castShadows(Hh, half, vScale * 0.5, fast ? 24 : 56);
  const aoHalf = horizonAO(Hh, half, vScale * 0.5, fast ? 4 : 10, fast ? 8 : 18);
  const shadowF = upsample(shadowHalf, half, size);
  const aoF = upsample(aoHalf, half, size);
  const Hb = blurWrap(H, size, Math.max(2, Math.round(size / 48)));

  const ambient = material.ambient ?? 0.34;
  const shine = material.shine ?? 28;
  const aoK = (material.ao ?? 1) * STYLE.shade;
  const aoFloor = material.aoFloor ?? 0.3;
  const rough = material.rough ?? (() => 0.7);

  const albedoBuf = Buffer.allocUnsafe(size * size * 3);
  const surfFull = Buffer.allocUnsafe(size * size * 4);
  const prelitFull = Buffer.allocUnsafe(size * size * 3);

  // The half-vector for a viewer looking straight down at the tile.
  const hvx = LIGHT[0];
  const hvy = LIGHT[1];
  const hvz = LIGHT[2] + 1;
  const hvl = Math.hypot(hvx, hvy, hvz);

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = y * size + x;
      const h = H[i]!;
      // Central differences on the wrapped grid — the surface normal.
      const gx = H[y * size + wrap(x + 1, size)]! - H[y * size + wrap(x - 1, size)]!;
      const gy = H[wrap(y + 1, size) * size + x]! - H[wrap(y - 1, size) * size + x]!;
      const nx = -gx * material.relief * size * 0.02;
      const ny = -gy * material.relief * size * 0.02;
      const len = Math.hypot(nx, ny, 1);
      const ux = nx / len;
      const uy = ny / len;
      const uz = 1 / len;

      const u = (x + 0.5) / size;
      const v = (y + 0.5) / size;
      const occ = Math.max(aoFloor, clamp01(1 - (1 - aoF[i]!) * aoK));
      const surface: Surface = {
        h,
        slope: Math.hypot(nx, ny),
        // Positive in hollows: the blurred field sits above this pixel.
        curvature: (Hb[i]! - h) * 8,
        ao: occ,
        shadow: shadowF[i]!,
      };

      let [r, g, b] = material.albedo(u, v, surface, base);
      const sat = lerp(1, STYLE.sat, STYLE_FOLLOW);
      const tone = lerp(1, STYLE.tone, STYLE_FOLLOW);
      if (sat !== 1 || tone !== 1) {
        const lum = 0.299 * r + 0.587 * g + 0.114 * b;
        // Saturation around the pixel's own luminance, then a gain on the whole
        // thing. Both are low-frequency, so unlike the detail knobs they still
        // read once the texture has been mipped down to tile size.
        r = (lum + (r - lum) * sat) * tone;
        g = (lum + (g - lum) * sat) * tone;
        b = (lum + (b - lum) * sat) * tone;
      }
      const grain = STYLE.grain * STYLE_FOLLOW;
      if (grain > 0) {
        const n = (hash2(x, y, 977) - 0.5) * grain * 255;
        r += n;
        g += n;
        b += n;
      }
      const j3 = i * 3;
      albedoBuf[j3] = Math.round(clamp01(r / 255) * 255);
      albedoBuf[j3 + 1] = Math.round(clamp01(g / 255) * 255);
      albedoBuf[j3 + 2] = Math.round(clamp01(b / 255) * 255);

      const j4 = i * 4;
      surfFull[j4] = Math.round(clamp01(ux * 0.5 + 0.5) * 255);
      surfFull[j4 + 1] = Math.round(clamp01(uy * 0.5 + 0.5) * 255);
      // Occlusion carries the cast shadow: the board's light is fixed relative to
      // the board, so a baked shadow term stays correct there.
      surfFull[j4 + 2] = Math.round(
        Math.max(aoFloor, clamp01(occ * lerp(1, surface.shadow, STYLE.shade))) * 255,
      );
      surfFull[j4 + 3] = Math.round(clamp01(rough(u, v, surface)) * 255);

      const lambert = Math.max(0, ux * LIGHT[0] + uy * LIGHT[1] + uz * LIGHT[2]);
      const spec =
        material.gloss > 0
          ? material.gloss * Math.max(0, ux * (hvx / hvl) + uy * (hvy / hvl) + uz * (hvz / hvl)) ** shine
          : 0;
      const lit = (ambient + (1 - ambient) * lambert * surface.shadow) * occ;
      prelitFull[j3] = Math.round(clamp01((r * lit + 255 * spec * surface.shadow) / 255) * 255);
      prelitFull[j3 + 1] = Math.round(clamp01((g * lit + 255 * spec * surface.shadow) / 255) * 255);
      prelitFull[j3 + 2] = Math.round(clamp01((b * lit + 255 * spec * surface.shadow) / 255) * 255);
    }
  }

  return { albedo: albedoBuf, surface: surfFull, prelit: prelitFull };
}

// ---------------------------------------------------------------------------

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  if (i >= 0 && process.argv[i + 1]) return process.argv[i + 1]!;
  const inline = process.argv.find((a) => a.startsWith(`--${name}=`));
  return inline ? inline.slice(name.length + 3) : fallback;
}

async function main(): Promise<void> {
  const styleName = arg('style', 'stylised');
  const style = STYLES[styleName];
  if (!style) throw new Error(`unknown --style ${styleName}; expected ${Object.keys(STYLES).join(' | ')}`);
  STYLE = style;

  const size = Number.parseInt(arg('size', '1024'), 10);
  if (!Number.isFinite(size) || size < 64 || (size & (size - 1)) !== 0) {
    throw new Error(`bad --size ${size}; expected a power of two >= 64`);
  }
  const fast = process.argv.includes('--fast');
  const outDir = path.resolve(process.cwd(), arg('out', `public/terrain/${styleName}/${size}`));
  await mkdir(outDir, { recursive: true });

  const half = size >> 1;
  const surfaceDim = arg('surface', 'half') === 'full' ? size : half;
  const manifest: Record<string, { albedo: number; surface: number; prelit: number }> = {};
  let total = 0;
  const t0 = Date.now();

  for (const [terrain, hex] of Object.entries(TERRAIN_COLOR) as [Terrain, string][]) {
    const started = Date.now();
    const maps = render(MATERIALS[terrain], parseHex(hex), size, fast);
    const name = terrain.toLowerCase();

    const albedo = await sharp(maps.albedo, { raw: { width: size, height: size, channels: 3 } })
      .webp({ quality: 88, effort: 6 })
      .toBuffer();
    // Surface resolution is a knob, because it turns out to be the LIMITER at a
    // close camera. Measured at zoom 2.1 on a 1512px viewport, a tile projects to
    // 320-416 device pixels: the 1024 albedo supplies 2.5-3.2 texels per pixel
    // (oversupplied), while a half-res surface map supplies 1.2-1.6 (about 1:1).
    // Relief detail is therefore the first thing to soften, not colour.
    const surface = await sharp(maps.surface, { raw: { width: size, height: size, channels: 4 } })
      .resize(surfaceDim, surfaceDim)
      // Near-lossless: a lossy normal map produces blocky lighting, because the
      // artefacts land in the derivative rather than in the colour.
      .webp({ nearLossless: true, quality: 80, effort: 6 })
      .toBuffer();
    const prelit = await sharp(maps.prelit, { raw: { width: size, height: size, channels: 3 } })
      .resize(half, half)
      .webp({ quality: 88, effort: 6 })
      .toBuffer();

    await writeFile(path.join(outDir, `${name}.webp`), albedo);
    await writeFile(path.join(outDir, `${name}-s.webp`), surface);
    await writeFile(path.join(outDir, `${name}-p.webp`), prelit);
    manifest[name] = { albedo: albedo.length, surface: surface.length, prelit: prelit.length };
    total += albedo.length + surface.length + prelit.length;
    const kb = (n: number) => `${(n / 1024).toFixed(0)}K`.padStart(5);
    console.log(
      `  ${terrain.padEnd(10)} ${hex}  albedo ${kb(albedo.length)}  surface ${kb(surface.length)}` +
        `  prelit ${kb(prelit.length)}   ${((Date.now() - started) / 1000).toFixed(1)}s`,
    );
  }

  await writeFile(
    path.join(outDir, 'manifest.json'),
    `${JSON.stringify({ style: styleName, size, surface: surfaceDim, fast, maps: manifest }, null, 2)}\n`,
  );
  console.log(
    `\n${Object.keys(manifest).length} terrains — ${styleName} @ ${size} — ` +
      `${(total / 1024 / 1024).toFixed(2)} MB in ${((Date.now() - t0) / 1000).toFixed(0)}s -> ${outDir}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
